# Site Settings
title: My Resume
url: 'https://lizzyt10h.github.io'
baseurl: '' #change it according to your repository name
about: True # set to False or comment line if you want to remove the "How to use?" in the sidebar


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Lizzy Tengana
tagline: Systems and Computer Engineering student
pic: lizzy_profile.jpg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: "A passionate and responsible undergraduate student seeking to broaden
          her career horizons and gain new skills. Being also a self-motivated 
          learner aimed to achieve high academic performance and with deep interest
          in data management, parallel and distributed computing and software engineering.
          <br><br>
          Currently working on blockchain projects and diving into the cryptocurrencies' world."

#sidebar links
email: lizzyt10h@gmail.com
website: lizzyt10h.github.io #do not add http://
linkedin: lizzyt10h
github: lizzyt10h
twitter: '@lizzyt10h'
#Update all the sections by editing the files inside _data folder.

# uncomment the next line, if you want the education section displayed in main instead of the sidebar
#education_in_main: True

# Tracker
# analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
